from langchain_openai import ChatOpenAI
from utils.logger import get_logger

logger = get_logger(__name__)

_llm = None


def get_llm():
    global _llm
    if _llm is None:
        _llm = ChatOpenAI(model="gpt-4o-mini", temperature=0.6)
    return _llm


async def writer_node(state: dict) -> dict:
    topic = state["topic"]
    research_notes = state["research_notes"]
    revision_count = state.get("revision_count", 0)

    logger.info(f"[WRITER] Drafting report. Revision #{revision_count}")

    llm = get_llm()

    revision_note = ""
    if revision_count > 0:
        revision_note = (
            f"\n\nIMPORTANT: This is revision #{revision_count}. "
            "Significantly improve depth, concrete examples, and analytical clarity compared to the previous draft."
        )

    prompt = f"""You are an expert technical writer. Using the research notes below, write a comprehensive, professional report.

Topic: {topic}

Research Notes:
{research_notes}{revision_note}

Write the full report in Markdown using this exact structure:

# [Compelling, Specific Report Title]

## Executive Summary
[2–3 substantive paragraphs summarising key findings and their implications]

## Introduction
[Background, context, why this topic matters, and scope of the report]

## Key Findings
[Major discoveries, insights, and data points — use sub-bullets where helpful]

## In-Depth Analysis
### [Relevant Aspect 1]
[Detailed analysis with examples]

### [Relevant Aspect 2]
[Detailed analysis with examples]

### [Relevant Aspect 3]
[Detailed analysis with examples]

## Challenges and Considerations
[Obstacles, risks, limitations, and important factors]

## Future Outlook
[Trends, predictions, and strategic implications]

## Conclusion
[Summary of key insights, actionable takeaways, and closing thoughts]

---
*Generated by AI Report Generator — Multi-Agent System (Researcher → Writer → Editor)*

Requirements:
- Professional, authoritative language
- Each major section: 3–5 substantial paragraphs
- Specific data points and examples from the research
- Consistent, engaging tone throughout"""

    response = llm.invoke(prompt)
    draft_report = response.content

    logger.info(f"[WRITER] Draft complete — {len(draft_report)} chars")

    return {
        **state,
        "draft_report": draft_report,
        "status": "drafted",
    }
